name = "PyScriptWidgets"

packages = [
    "asyncio",
]

[files]
"{BASE}" = "/PyScriptWidgets"
"{BASE}/widgets.py" = "./widgets.py"
"{BASE}/todo.py" = "./todo.py"

# See: https://pyscript.github.io/docs/2024.1.3/user-guide/configuration/#files
